import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from "@/app/ui/Navbar/Navbar";
import React from "react";
import Footer from "@/app/ui/Footer/Footer";
import Window from "@/ui/Window/Window";
import LaunchedGamePackage from "@/app/library/ui/LaunchedGamePackage/LaunchedGamePackage";
import {gameLibraryStore} from "@/app/store";
import LaunchedGameWindow from "@/app/ui/LaunchedGameWindow/LaunchedGameWindow";
import LayoutWrap from "@/app/layout-wrap";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Steam GameUi Launcher',
  description: 'Generated by create next app',
}

const Layout = ({children}) => {

  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutWrap>
          {children}
        </LayoutWrap>
        <LaunchedGameWindow />
      </body>
    </html>
  )
}

export default Layout;
